
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - airship.airshipit.org
  resources:
  - sipclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - airship.airshipit.org
  resources:
  - sipclusters/status
  verbs:
  - get
  - patch
  - update
