apiVersion: airship.airshipit.org/v1
kind: SIPCluster
metadata:
  name: sipcluster-test1
  namespace: sipcluster-system
  finalizers:
    - sip.airship.airshipit.org/finalizer
spec:
    config:
        cluster-name: subcluster-test1
    nodes:
      worker:
          vm-flavor: 'airshipit.org/vino-flavor=worker'
          scheduling-constraints: ['per-node'] # Support dont'care option.
          count:
              active: 2 #driven by capi node number
              standby: 1 #slew for upgrades etc
      master:
          vm-flavor: 'airshipit.org/vino-flavor=master'
          scheduling-constraints: ['per-node','per-rack']
          count:
              active: 1
              standby: 1
    infra:
        loadbalancer:
          optional:
            clusterIp: 1.2.3.4 #<-- this aligns to the VIP IP for undercloud k8s
          image: haproxy:foo
          nodeLabels:
              - airship-masters
          nodePorts:
              - 7000
              - 7001
              - 7002
          nodeInterfaceId: oam-ipv4
        jumppod:
          optional:
            sshKey: rsa.... #<-- this needs to align to the ssh keys provided to cluster api objects
          image: sshpod:foo
          nodeLabels:
            - airship-masters
          nodePorts:
            -  7022
          nodeInterfaceId: oam-ipv4
        authpod:
          image: sshpod:foo
          nodeLabels:
            - airship-masters
          nodePorts:
            - 7023
          nodeInterfaceId: oam-ipv4

