apiVersion: airship.airshipit.org/v1
kind: SIPCluster
metadata:
  name: sipcluster-test1
  namespace: sipcluster-system
  finalizers:
    - sip.airship.airshipit.org/finalizer
spec:
    clusterName: subcluster-test1
    nodes:
      Worker:
          vmFlavor: 'vino.airshipit.org/flavor=worker'
          spreadTopology: 'PerHost' # Support dont'care option.
          count:
              active: 1 #driven by capi node number
              standby: 1 #slew for upgrades etc
      ControlPlane:
          vmFlavor: 'vino.airshipit.org/flavor=control-plane'
          spreadTopology: 'PerRack'
          count:
              active: 1
              standby: 1
    infra:
      - serviceType: auth
        image: sshpod:foo
        nodeLabels:
          - airship-control-plane
        nodePort: 7023
        nodeInterfaceId: oam-ipv4
      - serviceType: jumphost
        redfish:
          proxy: false
        image: quay.io/airshipit/jump-host:dev
        nodeLabels:
          - airship-control-plane
        nodePort: 7022
        nodeInterfaceId: oam-ipv4
      - serviceType: loadbalancer
        image: haproxy:2.3.2
        nodeLabels:
          - airship-control-plane
        nodePort: 30000
        nodeInterfaceId: oam-ipv4
