#!/bin/bash

#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

# Update git index
git update-index -q --ignore-submodules --refresh

# Evaluate git files for difference, if found print message and fail.
git diff --exit-code --ignore-submodules
if [ $? -ne 0 ]
then
    echo "error: git diff found, please run make test"
    exit 1
fi

echo "success: git diff not found"
