- hosts: ubuntu-focal
  tasks:
    - name: Run docker-install
      include_role:
        name: docker-install
    - name: Install Dependent Packages
      apt:
        pkg:
          - debconf
          - make
          - snapd
      become: yes
    - name:  Set up requirements for kubernetes
      include_role:
        name: clear-firewall
    - name: Install kubernetes and Deploy Sip
      shell: |
        set -xe;
        ./tools/deployment/install-k8s.sh
        ./tools/deployment/deploy-sip.sh
      args:
        chdir: "{{ zuul.project.src_dir }}"
