- hosts: ubuntu-focal
  environment:
    GOROOT: '/usr/local/go'
    GOBIN: /tmp/bin/
    PATH: /usr/local/go/bin:/tmp/bin/:/usr/local/kubebuilder/bin:{{ ansible_env.PATH }}
  tasks:
    - name: set default vars
      set_fact:
        var_files_default:
          - airship-sip.yaml
    - name: read test variables
      include_vars:
        file: "vars/{{ var_file }}"
      with_items: "{{ var_files | default(var_files_default) }}"
      loop_control:
        loop_var: var_file
    - name: Install Dependent Packages
      package:
        name:
          - debconf
          - runc
          - make
          - build-essential
        update_cache: yes
        state: present
      become: yes
    - name: Run docker-install
      include_role:
        name: docker-install
    - name: Download Extract and install Golang
      become: yes
      unarchive:
        src: https://golang.org/dl/go{{airship_sip.go_lang.go_version}}.linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: yes
    - name: Download Extract and install Kubebuilder
      become: yes
      shell: |
        curl -L -o - https://github.com/kubernetes-sigs/kubebuilder/releases/download/v{{airship_sip.kube_builder.kube_version}}/kubebuilder_{{airship_sip.kube_builder.kube_version}}_linux_amd64.tar.gz | tar -xz -C /usr/local --one-top-level=kubebuilder --strip-components 1
      args:
        executable: /bin/bash
    - name: Run test suite
      make:
        chdir: "{{ zuul.project.src_dir }}"
        target: test
    - name: Check git diff
      make:
        chdir: "{{ zuul.project.src_dir }}"
        target: check-git-diff
    - name: Build SIP Docker image
      make:
        chdir: "{{ zuul.project.src_dir }}"
        target: docker-build-controller
    - name: Build Jump Host Docker image
      make:
        chdir: "{{ zuul.project.src_dir }}"
        target: docker-build-jump-host
